project_id = "ophcmzlrkqaoebhpupjs"

[functions.ai-tutor]
verify_jwt = false

[functions.ai-paper]
verify_jwt = false

[functions.ai-notes]
verify_jwt = false

[functions.ai-classify]
verify_jwt = false

[functions.ai-exam]
verify_jwt = false

[functions.ai-revision]
verify_jwt = false
