// Modified wrapper: delegate OAuth start to our app auth server to avoid opening Lovable's hosted consent UI for user sign-ins.
// NOTE: This file was originally generated by Lovable; we intentionally override the OAuth sign-in path here so
// that the app always uses our backend for user authentication flows. If you regenerate Lovable files, re-apply this change.

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    // Start an OAuth sign-in by asking our backend for the authorization URL or tokens.
    // Backend endpoints expected:
    // - GET /auth/oauth/start?provider=google|github|apple[&redirect_uri=...]
    //    -> returns { url: string } for hosted redirects OR { tokens: { access_token, refresh_token } }
    // - If your backend implements a popup/PKCE flow it can also return tokens directly.
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      try {
        const params = new URLSearchParams();
        params.set("provider", provider);
        if (opts?.redirect_uri) params.set("redirect_uri", opts.redirect_uri);
        // include any extra params
        if (opts?.extraParams) {
          Object.entries(opts.extraParams).forEach(([k, v]) => params.set(k, v));
        }

        const resp = await fetch(`/auth/oauth/start?${params.toString()}`, {
          method: "GET",
          credentials: "include",
          headers: { "Accept": "application/json" },
        });

        if (!resp.ok) {
          let body: any;
          try { body = await resp.json(); } catch (_) { body = null; }
          return { error: body?.error || new Error('OAuth start failed') } as any;
        }

        const body = await resp.json();

        // If backend returned a redirect URL (hosted flow), tell caller and include url so the app can navigate.
        if (body.url) {
          return { redirected: true, url: body.url } as any;
        }

        // If backend returned tokens (already-authenticated), pass them through.
        if (body.tokens) {
          return { tokens: body.tokens } as any;
        }

        // Otherwise return the raw body.
        return body as any;
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) } as any;
      }
    },
  },
};
