/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsPaperIdRouteImport } from './routes/tests.$paperId'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as TestsPaperIdPreviewRouteImport } from './routes/tests.$paperId.preview'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsPaperIdRoute = TestsPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => TestsRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesRoute,
} as any)
const TestsPaperIdPreviewRoute = TestsPaperIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => TestsPaperIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/exams': typeof ExamsRoute
  '/home': typeof HomeRoute
  '/notes': typeof NotesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tests': typeof TestsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/workspace': typeof WorkspaceRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/tests/$paperId': typeof TestsPaperIdRouteWithChildren
  '/tests/$paperId/preview': typeof TestsPaperIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/exams': typeof ExamsRoute
  '/home': typeof HomeRoute
  '/notes': typeof NotesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tests': typeof TestsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/workspace': typeof WorkspaceRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/tests/$paperId': typeof TestsPaperIdRouteWithChildren
  '/tests/$paperId/preview': typeof TestsPaperIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/exams': typeof ExamsRoute
  '/home': typeof HomeRoute
  '/notes': typeof NotesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tests': typeof TestsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/workspace': typeof WorkspaceRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/tests/$paperId': typeof TestsPaperIdRouteWithChildren
  '/tests/$paperId/preview': typeof TestsPaperIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator'
    | '/dashboard'
    | '/donate'
    | '/exams'
    | '/home'
    | '/notes'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/tasks'
    | '/tests'
    | '/timetable'
    | '/tutor'
    | '/workspace'
    | '/notes/$noteId'
    | '/tests/$paperId'
    | '/tests/$paperId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/dashboard'
    | '/donate'
    | '/exams'
    | '/home'
    | '/notes'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/tasks'
    | '/tests'
    | '/timetable'
    | '/tutor'
    | '/workspace'
    | '/notes/$noteId'
    | '/tests/$paperId'
    | '/tests/$paperId/preview'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calculator'
    | '/dashboard'
    | '/donate'
    | '/exams'
    | '/home'
    | '/notes'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/tasks'
    | '/tests'
    | '/timetable'
    | '/tutor'
    | '/workspace'
    | '/notes/$noteId'
    | '/tests/$paperId'
    | '/tests/$paperId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  ExamsRoute: typeof ExamsRoute
  HomeRoute: typeof HomeRoute
  NotesRoute: typeof NotesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevisionRoute: typeof RevisionRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TestsRoute: typeof TestsRouteWithChildren
  TimetableRoute: typeof TimetableRoute
  TutorRoute: typeof TutorRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$paperId': {
      id: '/tests/$paperId'
      path: '/$paperId'
      fullPath: '/tests/$paperId'
      preLoaderRoute: typeof TestsPaperIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/tests/$paperId/preview': {
      id: '/tests/$paperId/preview'
      path: '/preview'
      fullPath: '/tests/$paperId/preview'
      preLoaderRoute: typeof TestsPaperIdPreviewRouteImport
      parentRoute: typeof TestsPaperIdRoute
    }
  }
}

interface NotesRouteChildren {
  NotesNoteIdRoute: typeof NotesNoteIdRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNoteIdRoute: NotesNoteIdRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface TestsPaperIdRouteChildren {
  TestsPaperIdPreviewRoute: typeof TestsPaperIdPreviewRoute
}

const TestsPaperIdRouteChildren: TestsPaperIdRouteChildren = {
  TestsPaperIdPreviewRoute: TestsPaperIdPreviewRoute,
}

const TestsPaperIdRouteWithChildren = TestsPaperIdRoute._addFileChildren(
  TestsPaperIdRouteChildren,
)

interface TestsRouteChildren {
  TestsPaperIdRoute: typeof TestsPaperIdRouteWithChildren
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsPaperIdRoute: TestsPaperIdRouteWithChildren,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  ExamsRoute: ExamsRoute,
  HomeRoute: HomeRoute,
  NotesRoute: NotesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RevisionRoute: RevisionRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TestsRoute: TestsRouteWithChildren,
  TimetableRoute: TimetableRoute,
  TutorRoute: TutorRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
