/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsPaperIdRouteImport } from './routes/tests.$paperId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsPaperIdRoute = TestsPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => TestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/notes': typeof NotesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tests': typeof TestsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/workspace': typeof WorkspaceRoute
  '/tests/$paperId': typeof TestsPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/notes': typeof NotesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tests': typeof TestsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/workspace': typeof WorkspaceRoute
  '/tests/$paperId': typeof TestsPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/notes': typeof NotesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tests': typeof TestsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/tutor': typeof TutorRoute
  '/workspace': typeof WorkspaceRoute
  '/tests/$paperId': typeof TestsPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/notes'
    | '/revision'
    | '/settings'
    | '/tasks'
    | '/tests'
    | '/timetable'
    | '/tutor'
    | '/workspace'
    | '/tests/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/home'
    | '/notes'
    | '/revision'
    | '/settings'
    | '/tasks'
    | '/tests'
    | '/timetable'
    | '/tutor'
    | '/workspace'
    | '/tests/$paperId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/notes'
    | '/revision'
    | '/settings'
    | '/tasks'
    | '/tests'
    | '/timetable'
    | '/tutor'
    | '/workspace'
    | '/tests/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  NotesRoute: typeof NotesRoute
  RevisionRoute: typeof RevisionRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TestsRoute: typeof TestsRouteWithChildren
  TimetableRoute: typeof TimetableRoute
  TutorRoute: typeof TutorRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$paperId': {
      id: '/tests/$paperId'
      path: '/$paperId'
      fullPath: '/tests/$paperId'
      preLoaderRoute: typeof TestsPaperIdRouteImport
      parentRoute: typeof TestsRoute
    }
  }
}

interface TestsRouteChildren {
  TestsPaperIdRoute: typeof TestsPaperIdRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsPaperIdRoute: TestsPaperIdRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  NotesRoute: NotesRoute,
  RevisionRoute: RevisionRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TestsRoute: TestsRouteWithChildren,
  TimetableRoute: TimetableRoute,
  TutorRoute: TutorRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
