plugins {
    id 'com.android.application'
}

android {
    namespace 'com.insightly.app'

    compileSdk 36

    defaultConfig {
        applicationId "com.insightly.app"

        minSdk 21
        targetSdk 36

        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            if (project.hasProperty('android.injected.signing.store.file')) {
                storeFile file(project.property('android.injected.signing.store.file'))
                storePassword project.property('android.injected.signing.store.password')
                keyAlias project.property('android.injected.signing.key.alias')
                keyPassword project.property('android.injected.signing.key.password')
            } else {
                def keystorePropertiesFile = rootProject.file('key.properties')

                if (keystorePropertiesFile.exists()) {
                    def Properties keystoreProperties = new Properties()

                    keystoreProperties.load(
                        new FileInputStream(keystorePropertiesFile)
                    )

                    storeFile file(keystoreProperties['storeFile'])
                    storePassword keystoreProperties['storePassword']
                    keyAlias keystoreProperties['keyAlias']
                    keyPassword keystoreProperties['keyPassword']
                }
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled false

            proguardFiles(
                getDefaultProguardFile('proguard-android-optimize.txt'),
                'proguard-rules.pro'
            )
        }
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation 'com.getcapacitor:capacitor-android:5.7.8'
}
